Echo response messages for `sbf_archive_main()` and `sbf_rm_main()`
poissonconsulting/subfoldr2 pull request #102
Opened 2024-07-12 19:42 UTC by dunkenwg

- Added echo response messages for both `sbf_archive_main()` and `sbf_rm_main()` (computer tells user what option they chose)
- Added tests for echo messages
- Removed extraneous test messages

2024-07-13 19:05 UTC, dunkenwg commented
Also alphabetized description imports

2024-07-15 21:48 UTC, aylapear requested changes
Can you re-run the documentation so the roxygen version updates? To do this click on the Build tab > More > Document.

2024-07-16 23:29 UTC, aylapear approved these changes

2024-07-17 15:55 UTC, aylapear approved these changes

2024-07-17 15:55 UTC, merged