Checking subfoldr2
poissonconsulting/subfoldr2 pull request #105
Opened 2024-09-12 04:30 UTC by dunkenwg

2024-09-16 18:13 UTC, dunkenwg commented
Tests fail locally but pass on GitHub

2024-09-17 12:20 UTC, joethorley approved these changes
Thanks!

2024-09-17 12:20 UTC, joethorley commented on .github/workflows/R-CMD-check.yaml
> +name: R-CMD-check.yaml
```suggestion
name: R-CMD-check
```

We want to avoid `.yaml` appearing in the badge.

2024-09-17 12:20 UTC, joethorley commented on .github/workflows/R-CMD-check.yaml
> +          - {os: ubuntu-latest,  r: 'oldrel-4'}
```suggestion
          - {os: ubuntu-latest,  r: 'oldrel-1'}
```
I'm thinking all these tests are overkill for a package that is really just used by Poisson folks and so should be used on an up to date OS

2024-09-17 12:21 UTC, joethorley commented
> Tests fail locally but pass on GitHub

What is the fail message?

2024-09-17 16:04 UTC, dunkenwg commented
All 22 test failures have to do with connection to the server:
```
Error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
```
or
```
Error in `h(simpleError(msg, call))`: error in evaluating the argument 'conn' in selecting a method for function 'dbDisconnect': object 'conn' not found
```
or
```
Error: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
```
Is this because these tests only connect to the server when run on GitHub?

2024-09-18 13:17 UTC, joethorley requested changes
I'm getting the same error

Error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
Is the server running locally and accepting connections on that socket?

I'm wondering if the database is down? This is a question for Ayla when she returns and settles in.

2024-09-24 23:51 UTC, aylapear commented
Those tests are skipped on CI which is why it is passing in GitHub but failing locally. The issue is you need to have a local Postgres database set up for the tests to run. It is more then just have the `psql` package installed or having Postgres installed as external software. @dunkenwg give me a shout and I can explain further and maybe we can figure out a creative solution for testing if a person has an internal psql database set up locally before running those tests and if not it skips them.

2024-09-25 00:01 UTC, aylapear reviewed
Looks good other then the comments I posted that we should look into before merging

2024-09-27 20:45 UTC, aylapear approved these changes
Changes look good but should chat about the test failures before merging.

2024-10-16 03:06 UTC, joethorley approved these changes

2024-10-31 17:04 UTC, dunkenwg commented
Update data analysis book in section 9.5: have to have local postgres username database set up
```
duncan@duncans-mbp ~ % psql
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?

duncan@duncans-mbp ~ % brew services restart postgresql

duncan@duncans-mbp ~ % psql postgres
psql (14.13 (Homebrew))
Type "help" for help.
postgres-# \q

duncan@duncans-mbp ~ % createdb duncan
duncan@duncans-mbp ~ % psql
psql (14.13 (Homebrew))
Type "help" for help.
duncan=# 
```

2024-10-31 17:48 UTC, merged